//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Product = new HashSet<Product>();
        }

        [Display(Name = "Đường Dẫn URL")]
        [Required(ErrorMessage = "URL Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "URL Không Được Vượt Quá 250 Kí Tự")]
        [Index(IsUnique = true)]
        [Column(TypeName = "varchar")]
        public string Alias { get; set; }
        [Display(Name = "Ảnh đại diện")]
        [MaxLength(500)]
        public string Images { get; set; }
        public string Author { get; set; }
        [Display(Name = "Ngày đăng")]
        public Nullable<System.DateTime> CreatedAt { get; set; }
        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }
        public int CategoryID { get; set; }
        [Display(Name = "Tên Nhóm Sản Phẩm")]
        [Required(ErrorMessage = "Tên Nhóm Sản Phẩm Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Tên Nhóm Sản Phẩm  Không Được Vượt Quá 250 Kí Tự")]
        public string CategoryName { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
    }
}
