//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Configure
    {
        public int ConfigID { get; set; }
        [Display(Name = "Logo Website")]
        [MaxLength(256, ErrorMessage = "Tên File Logo Quá Dài Vui Lòng Đổi Lại tên")]
        public string Logo { get; set; }
        [Display(Name = "Icon Favicon")]
        [MaxLength(256, ErrorMessage = "Tên File Favicon Quá Dài Vui Lòng Đổi Lại tên")]
        public string Favicon { get; set; }
        [Display(Name = "Tên Công Ty,Doanh Nghiệp")]
        [MaxLength(256, ErrorMessage = "Tên Công Ty,Doanh Nghiệp Không Được Quá 256 Kí Tự")]
        public string NameCompany { get; set; }

        [Display(Name = "Mô tả Công Ty,Doanh Nghiệp")]
        public string Description { get; set; }
        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }
        [Display(Name = "Email")]
        [MaxLength(50, ErrorMessage = "Email Không Được Quá 50 Kí Tự")]
        public string Email { get; set; }
        [Display(Name = "Email Nhận Tin Khách Hàng")]
        [MaxLength(50, ErrorMessage = "Email Nhận Tin Không Được Quá 50 Kí Tự")]
        public string EmailReceive { get; set; }
        [Display(Name = "Số Điện Thoại")]
        [MaxLength(11, ErrorMessage = "Số Điện Thoại Không Hợp Lệ")]
        public string Phone { get; set; }
        [Display(Name = "Hotline")]
        [MaxLength(150, ErrorMessage = "Hotline Tối Đa Là 150 Kí Tự")]
        public string Hotline { get; set; }
        [AllowHtml]
        [Display(Name = "Mã Nhúng Google Map")]
        public string Map { get; set; }

        [AllowHtml]
        [Display(Name = "Mã Nhúng FANPAGE FACEBOOK")]
        public string FanpageFacebook { get; set; }
        public string IconFacebook { get; set; }
        public string IconTwiiter { get; set; }
        public string IconInstagram { get; set; }
        public string IconYoutube { get; set; }
        public string IconGoogle { get; set; }
        public string MetaTitle { get; set; }
        public string MetaKeyword { get; set; }
        public string MetaDescription { get; set; }
    }
}
