//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }

        public int orderID { get; set; }
        [Display(Name = "Phương thức thanh toán")]
        public int PaymentID { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0₫}")]
        [Display(Name = "Tổng Tiền")]
        public decimal TotalMoney { get; set; }
        [Display(Name = "Ngày đặt hàng")]
        public Nullable<System.DateTime> CreatedAt { get; set; }

        public bool ViewStatus { get; set; }
        [Display(Name = "Trạng Thái Đơn Hàng")]
        public long Status { get; set; }
        [Display(Name = "Ghi Chú")]
        public string Note { get; set; }
        public Nullable<int> customerID { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Payment Payment { get; set; }
        public Nullable<int> IdVoucher { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
