//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{

    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ImageProduct = new HashSet<ImageProduct>();
            this.OrderDetail = new HashSet<OrderDetail>();
        }

        public int ProductID { get; set; }
        [Display(Name = "Tên Sản Phẩm")]
        [Required(ErrorMessage = "Tên Sản Phẩm Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "Tên Sản Phẩm Không Được Vượt Quá 250 Kí Tự")]
        public string ProductName { get; set; }
        [Display(Name = "Đường Dẫn URL")]
        [Required(ErrorMessage = "URL Không Được Bỏ Trống")]
        [MaxLength(250, ErrorMessage = "URL Không Được Vượt Quá 250 Kí Tự")]
        [Index(IsUnique = true)]
        [Column(TypeName = "varchar")]
        public string Alias { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0₫}")]
        [Display(Name = "Giá sản phẩm")]
        public Nullable<decimal> Price { get; set; }

        [DisplayFormat(DataFormatString = "{0:0,0₫}")]
        [Display(Name = "Giá so sánh")]
        public Nullable<decimal> PriceSale { get; set; }
        [Display(Name = "Ảnh sản phẩm")]
        public string Images { get; set; }
        [Display(Name = "Số Lượng")]
        [Required(ErrorMessage = "Số Lượng Không Được Bỏ Trống")]
        public int Quanlity { get; set; }
        [Display(Name = "Nhóm Sản Phẩm")]
        public int CategoryID { get; set; }
        [Display(Name = "Mô tả ngắn")]
        [AllowHtml]
        public string DescriptShort { get; set; }
        [AllowHtml]
        [Column(TypeName = "ntext")]
        [Display(Name = "Nội Dung")]
        public string Content { get; set; }

        public string Author { get; set; }
        [Display(Name = "Mô tả")]
        public string MetaDescription { get; set; }
        [Display(Name = "Ngày đăng")]
        public Nullable<System.DateTime> CreatedAt { get; set; }
        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }
        [DisplayFormat(DataFormatString = "{0:0,0₫}")]
        [Display(Name = "Giá gốc sản phẩm")]
        public Nullable<decimal> PriceIn { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageProduct> ImageProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
