//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Slide
    {
        public int SliderID { get; set; }
        [Display(Name = "Thứ tự sắp xếp")]
        [Required(ErrorMessage = "Thứ tự sắp xếp không được bỏ trống")]
        public int SortID { get; set; }
        [Display(Name = "Tên Slide")]
        [MaxLength(250, ErrorMessage = "Tên Sản Phẩm Không Được Vượt Quá 250 Kí Tự")]

        public string SliderName { get; set; }
        [Display(Name = "Mô tả Slide")]
        public string Description { get; set; }
        [Display(Name = "Hình Ảnh Slide")]
        public string Images { get; set; }
        [Display(Name = "URL Liên Kết")]
        [MaxLength(250, ErrorMessage = "URL liên kết Không Được Vượt Quá 250 Kí Tự")]

        public string URL { get; set; }
        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }
    }
}
