//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;

    public partial class MenuNavigation
    {
        public int MenuID { get; set; }
        [Display(Name = "Thứ tự hiển thị")]
        public Nullable<int> Sequence { get; set; }

        [Display(Name = "Tên Menu")]
        [Required(ErrorMessage = "Tên Menu Không Được Bỏ Trống")]
        [MaxLength(50, ErrorMessage = "Tên Menu Không Được Quá 50 Kí Tự")]
        public string MenuName { get; set; }
        [Display(Name = "Icon hình ảnh")]
        public string IconMenu { get; set; }
        [Display(Name = "Chọn Cấp Thư Mục")]
        public int MenuParents { get; set; }
        [Display(Name = "Chọn Cấp Thư Mục")]
        public int PageStyle { get; set; }

        [Display(Name = "Chọn Cấp Thư Mục")]
        public Nullable<int> FormatPage { get; set; }
        [Display(Name = "Nhóm Liên Kết")]
        public Nullable<int> GroupLink { get; set; }
        [AllowHtml]
        [Column(TypeName = "ntext")]
        [Display(Name = "Trang Nội Dung")]
        public string PageContent { get; set; }

        [Display(Name = "Link Liên Kết")]
        [MaxLength(250, ErrorMessage = "Link Liên Kết Không Được Quá 250 Kí Tự")]

        public string PageLink { get; set; }
        [Display(Name = "Ngày Tạo")]
        public Nullable<System.DateTime> CreatedAt { get; set; }

        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }
    }
}
