//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Order = new HashSet<Order>();
        }

        public int PaymentID { get; set; }
        [Required(ErrorMessage = "Phương thức thanh toán Không Được Bỏ Trống")]
        [Display(Name = "Tên Phương Thức Thanh Toán")]
        public string PaymentName { get; set; }
        [Display(Name = "Ngày tạo")]
        public Nullable<System.DateTime> CreatedAt { get; set; }
        [Display(Name = "Trạng Thái")]
        public bool Status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
